"""Pydantic models for trading data and analysis."""

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field
from enum import Enum


class SignalType(str, Enum):
    """Trading signal types."""
    BUY = "buy"
    SELL = "sell"
    HOLD = "hold"
    STRONG_BUY = "strong_buy"
    STRONG_SELL = "strong_sell"


class ConfidenceLevel(str, Enum):
    """Confidence levels for recommendations."""
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    VERY_HIGH = "very_high"


class TimeSeriesData(BaseModel):
    """Time series data point from TimescaleDB."""
    timestamp: datetime
    symbol: str
    open: float
    high: float
    low: float
    close: float
    volume: float
    additional_data: Optional[dict] = None


class TechnicalIndicators(BaseModel):
    """Technical analysis indicators."""
    sma_20: Optional[float] = None
    sma_50: Optional[float] = None
    sma_200: Optional[float] = None
    ema_12: Optional[float] = None
    ema_26: Optional[float] = None
    rsi: Optional[float] = None
    macd: Optional[float] = None
    macd_signal: Optional[float] = None
    macd_histogram: Optional[float] = None
    bollinger_upper: Optional[float] = None
    bollinger_middle: Optional[float] = None
    bollinger_lower: Optional[float] = None
    atr: Optional[float] = None
    obv: Optional[float] = None


class TradingSignal(BaseModel):
    """Individual trading signal."""
    signal_type: SignalType
    indicator: str
    value: float
    description: str


class MarketAnalysis(BaseModel):
    """Comprehensive market analysis result."""
    symbol: str
    timestamp: datetime
    current_price: float
    price_change_24h: float
    price_change_7d: Optional[float] = None
    technical_indicators: TechnicalIndicators
    signals: list[TradingSignal]
    trend: str
    volatility: str
    support_levels: list[float] = []
    resistance_levels: list[float] = []


class TradingRecommendation(BaseModel):
    """Trading recommendation generated by the AI."""
    symbol: str
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    signal: SignalType
    confidence: ConfidenceLevel
    entry_price: Optional[float] = None
    stop_loss: Optional[float] = None
    take_profit: Optional[float] = None
    risk_reward_ratio: Optional[float] = None
    reasoning: str
    key_factors: list[str]
    risks: list[str]
    timeframe: str = "short_term"


class AnalysisRequest(BaseModel):
    """Request for market analysis."""
    symbol: str
    lookback_days: int = 30
    include_technical: bool = True
    include_sentiment: bool = False
    custom_prompt: Optional[str] = None


class AnalysisResponse(BaseModel):
    """Response containing analysis and recommendation."""
    request_id: str
    symbol: str
    timestamp: datetime
    analysis: MarketAnalysis
    recommendation: TradingRecommendation
    rag_context: list[str] = []
    model_used: str
    processing_time_ms: float


class RAGDocument(BaseModel):
    """Document stored in the RAG system."""
    id: str
    content: str
    metadata: dict
    timestamp: datetime
    symbol: Optional[str] = None
    document_type: str  # e.g., "analysis", "news", "pattern", "indicator"
